### ISSUE TITLE
Broken pip deps

### ISSUE THREAD

**Issue by wulfsolter** [sigvef/git-praise#1]
```
┌─[wulf@WULF-THINKPAD]-[2020-08-07 21:49 - 1596793765]-[~/code/somefolder] (somebranch)
└─[$]-> praise app.js
Traceback (most recent call last):
  File "/home/wulf/.local/bin/praise", line 5, in <module>
    from praise.main import praise_command
  File "/home/wulf/.local/lib/python3.8/site-packages/praise/main.py", line 3, in <module>
    from git.exc import InvalidGitRepositoryError
  File "/home/wulf/.local/lib/python3.8/site-packages/git/__init__.py", line 38, in <module>
    from git.config import GitConfigParser  # @NoMove @IgnorePep8
  File "/home/wulf/.local/lib/python3.8/site-packages/git/config.py", line 16, in <module>
    from git.compat import (
  File "/home/wulf/.local/lib/python3.8/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
```

which seems to be around https://github.com/gitpython-developers/GitPython/issues/983 and https://github.com/NervanaSystems/distiller/issues/475#issuecomment-589938449 has a nice summary.

**Comment by sigvef** [comment]
Thanks for the report!
